
version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      # Defina seu usuário, senha e banco de dados
      POSTGRES_USER: 'devuser'
      POSTGRES_PASSWORD: 'senha123'
      POSTGRES_DB: 'projeto_mobile'
    ports:
      - '5432:5432'
    volumes:
      # Armazena os dados do banco localmente para persistência
      - ./postgres-data:/var/lib/postgresql/data